### ISSUE TITLE
Add support plain_password_hex parameter

### ISSUE THREAD

**Issue by AlxndrLi** [Tw1sm/aesKrbKeyGen#1]
Hi!

secretsdump, when working in local mode (OfflineRegistry), gives out the plain password of the computer account in HEX format, as well as an NTLM hash, it does not give out AES keys, because it cannot get the machine and domain name. It would be cool to get AES keys for the password issued in HEX format for further use in getTGT, for example.

**Comment by Tw1sm** [comment]
Added support with 77d1c861b463a97dcfbeb878e1982ae3f07cfda3. Hex plaintext password from secretdump.py can be supplied with the `-pass` flag
